-- Supabase SQL Schema for TriageAI
-- Run this in your Supabase SQL Editor

-- 1. Triage History Table
CREATE TABLE IF NOT EXISTS triage_history (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now(),
  symptoms jsonb NOT NULL,
  result_level text NOT NULL,
  result_desc text NOT NULL,
  user_id text DEFAULT 'test-user-1'
);

-- 2. Chat Sessions Table
CREATE TABLE IF NOT EXISTS chat_sessions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now(),
  title text NOT NULL,
  user_id text DEFAULT 'test-user-1'
);

-- 3. Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now(),
  session_id uuid REFERENCES chat_sessions(id) ON DELETE CASCADE,
  type text NOT NULL, -- 'user' or 'bot'
  text text NOT NULL,
  user_id text DEFAULT 'test-user-1'
);

-- Note: Ensure existing table gets the column
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='chat_messages' AND column_name='session_id') THEN
    ALTER TABLE chat_messages ADD COLUMN session_id uuid REFERENCES chat_sessions(id) ON DELETE CASCADE;
  END IF;
END $$;

-- 4. Pharmacy Orders Table
CREATE TABLE IF NOT EXISTS pharmacy_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'Preparing',
  items jsonb NOT NULL,
  total_amount numeric NOT NULL,
  is_auto_refill boolean DEFAULT false,
  user_id text DEFAULT 'test-user-1'
);

-- Note: In a real app we'd use Supabase Auth and link `user_id` to auth.users.
-- For this prototype, we're defaulting 'test-user-1'.

-- Optional: Enable Row Level Security (RLS) but allow anon access for prototype
ALTER TABLE triage_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all operations for anon" ON triage_history;
CREATE POLICY "Enable all operations for anon" ON triage_history FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for anon" ON chat_sessions;
CREATE POLICY "Enable all operations for anon" ON chat_sessions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for anon" ON chat_messages;
CREATE POLICY "Enable all operations for anon" ON chat_messages FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for anon" ON pharmacy_orders;
CREATE POLICY "Enable all operations for anon" ON pharmacy_orders FOR ALL USING (true) WITH CHECK (true);
